/**
 * Upload API Client
 * 
 * Handles file uploads to the backend including:
 * - Single image upload
 * - Multiple images upload
 * - Document upload
 * - Avatar upload
 * - Resume upload
 */

import { apiClient } from '../api-client';
import { SuccessResponse } from '../types/api-response';

/**
 * Upload Response DTO matching backend structure
 * Backend returns: url, filename, originalName, mimetype, size, path
 * Note: thumbnailUrl is generated by the service but not exposed in DTO
 */
export interface UploadResponseDto {
    filename: string;
    originalName: string;
    mimetype: string;
    size: number;
    url: string;
    path: string;
}

/**
 * Upload a single image
 * 
 * @param file - File object to upload
 * @returns Upload response with file URL and metadata
 */
export async function uploadImage(
    file: File,
): Promise<UploadResponseDto> {
    const formData = new FormData();
    formData.append('file', file);

    return apiClient<UploadResponseDto>('/upload/image', {
        method: 'POST',
        body: formData,
        // extractData: true automatically extracts data from SuccessResponse
        extractData: true,
    });
}

/**
 * Upload multiple images
 * 
 * @param files - Array of File objects to upload (max 10)
 * @returns Array of upload responses with file URLs and metadata
 */
export async function uploadImages(
    files: File[],
): Promise<UploadResponseDto[]> {
    if (files.length === 0) {
        throw new Error('No files provided');
    }

    if (files.length > 10) {
        throw new Error('Maximum 10 files allowed');
    }

    const formData = new FormData();
    files.forEach((file) => {
        formData.append('files', file);
    });

    return apiClient<UploadResponseDto[]>('/upload/images', {
        method: 'POST',
        body: formData,
        // extractData: true automatically extracts data from SuccessResponse
        extractData: true,
    });
}

/**
 * Upload a document (PDF, DOC, DOCX, TXT)
 * 
 * @param file - File object to upload
 * @returns Upload response with file URL and metadata
 */
export async function uploadDocument(
    file: File,
): Promise<UploadResponseDto> {
    const formData = new FormData();
    formData.append('file', file);

    return apiClient<UploadResponseDto>('/upload/document', {
        method: 'POST',
        body: formData,
        // extractData: true automatically extracts data from SuccessResponse
        extractData: true,
    });
}

/**
 * Upload an avatar image
 * 
 * @param file - Image file to upload as avatar
 * @returns Upload response with file URL and metadata
 */
export async function uploadAvatar(
    file: File,
): Promise<UploadResponseDto> {
    const formData = new FormData();
    formData.append('file', file);

    return apiClient<UploadResponseDto>('/upload/avatar', {
        method: 'POST',
        body: formData,
        // extractData: true automatically extracts data from SuccessResponse
        extractData: true,
    });
}

/**
 * Upload a resume document
 * 
 * @param file - Resume file to upload (PDF, DOC, DOCX, TXT)
 * @returns Upload response with file URL and metadata
 */
export async function uploadResume(
    file: File,
): Promise<UploadResponseDto> {
    const formData = new FormData();
    formData.append('file', file);

    return apiClient<UploadResponseDto>('/upload/resume', {
        method: 'POST',
        body: formData,
        // extractData: true automatically extracts data from SuccessResponse
        extractData: true,
    });
}

